export enum ACTION_TYPES {
    GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS",
    ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION",
    STOP_SUBSCRIPTION = "STOP_SUBSCRIPTION",
    DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION",
    REMOVE_SUBSCRIPTIONS_ON_LOG_OUT = "REMOVE_SUBSCRIPTIONS_ON_LOG_OUT"
}