export enum ACTION_TYPES {
    GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS",
    ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION",
    STOP_SUBSCRIPTION = "STOP_SUBSCRIPTION",
    DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION"
}